name: Say hello

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-22.04
    steps:
      - name: Echo the message
        run: |
          echo "Hi, how are you?"
      - name: Dime la fecha
        run: date
      - run: ls -l